### ISSUE TITLE
Back to Results link does not appear on Resource Detail page when the browser back option is used

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/r4r-app#9] opened 2020-07-16 17:04 UTC
### Issue description
On Edge, "Back to Results" link does not appear on Resource Detail page when we visit the resource page and then use the browser back option.

> **ESTIMATE**

### Steps to reproduce the issue

On Edge (Prod):
1. Go to https://www.cancer.gov/research/resources/ 
2. Search with the term "cancer" from homepage
3. Select Datasets and DataBases from Tool Type
4. Click the resource "BioMuta" and notice that the "Back to Results" link appears
5. Click the "Visit Resource" button
6. Use the browser back option to return to the previous page
7. The "Back to Results" link does not appear on Resource Detail page

### What's the expected result?
- The "Back to Results" link should be displayed on returning to the resource Detail page from the external site.

### What's the actual result?
-The "Back to Results" link does not appear on Resource Detail page

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/87700800-eae8be00-c764-11ea-9566-e3aca00c5b4e.png)

**Comment by arcepaul** [comment] 2020-07-16 17:15
@alinai 
Are you saying this happens on Prod as well?  I'm not sure what IE (Prod) and Edge (Prod) means

**Comment by alinai** [comment] 2020-07-16 18:07
It is an existing issue on IE (Prod) and Edge (Prod and Dev). IE dev looks good.

**Comment by sarinapadilla** [comment] 2024-02-16 19:20
Can't reproduce this issue - closing!

**Closed by sarinapadilla** 2024-02-16 19:20 UTC
Labels: bug
